# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - j_coxa_1
    - j_femur_1
    - j_tibia_1
    - j_coxa_2
    - j_femur_2
    - j_tibia_2
    - j_coxa_3
    - j_femur_3
    - j_tibia_3
    - j_coxa_4
    - j_femur_4
    - j_tibia_4
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: leg_1_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j_coxa_1
      - j_femur_1
      - j_tibia_1
  - name: leg_2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j_coxa_2
      - j_femur_2
      - j_tibia_2
  - name: leg_3_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j_coxa_3
      - j_femur_3
      - j_tibia_3
  - name: leg_4_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j_coxa_4
      - j_femur_4
      - j_tibia_4